all:
	g++ -Wall regexToNFA.cpp -o regexToNFA
	g++ -Wall nfaToDfa.cpp -o nfaToDfa
	g++ -Wall DFAtoMinDFA.cpp -o minDFA
	g++ -Wall lexicalAnalyser.cpp -o lex
	
clean:
	rm -f regexToNFA nfaToDfa minDFA lex
